app:
    resource: "@AppBundle/Controller/"
    type:     annotation

m2iprojet_home_route:
    path     :  /
    defaults :  {  
                    _controller: AppBundle\Controller\WebServiceController::
                }
                
m2iprojet_presentation_route:
    path     :  /presentation
    defaults :  {  
                    _controller: AppBundle\Controller\WebServiceController::presentation
                }