home_route:
    path:      /home
    defaults:  { _controller: AppBundle\Controller\WebsiteController::home }

contact_route:
    path:      /contact
    defaults:  { _controller: AppBundle\Controller\WebsiteController::contact }

products_route:
    path:      /products
    defaults:  { _controller: AppBundle\Controller\WebsiteController::products }

forum_route:
    path:      /forum/{post_id}
    defaults:  { _controller: AppBundle\Controller\WebsiteController::forum, post_id:-1 }

classroomByName_route:
    path:      /classroom/{student_name}
    defaults:  { _controller: AppBundle\Controller\WebsiteController::classroomByName, student_name:'Johann' }
    requirements:
        student_name: '\D+'

classroomById_route:
    path:      /classroom/{student_id}
    defaults:  { _controller: AppBundle\Controller\WebsiteController::classroomById, student_id:0 }
    requirements:
        student_id: '\d+'

galery_route:
    path:      /galery/{img_id}
    defaults:  { _controller: AppBundle\Controller\WebsiteController::galery, img_id:0 }
