DROP DATABASE IF EXISTS `items`;
CREATE DATABASE IF NOT EXISTS `items`;

USE `items`;

DROP TABLE IF EXISTS `usable_items`;

CREATE TABLE IF NOT EXISTS `usable_items` (

	id TINYINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(50) UNIQUE NOT NULL DEFAULT "no_name",
	price INT NOT NULL DEFAULT "0",
	power INT NOT NULL DEFAULT "0",
	weight INT NOT NULL DEFAULT "0",
	mana_conso INT NOT NULL DEFAULT "0",
	health_recovery INT NOT NULL DEFAULT "0",
	hand_slot ENUM("UNKNOW","ONE","TWO") NOT NULL DEFAULT "UNKNOW"
);