AppBundle\Entity\Student:
    type: entity
    table: students
    repositoryClass: AppBundle\Repository\StudentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: '50'
        lastname:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
